server:
  port: 8181
spring:
  application:
    name: oauth
  main:
    show_banner: false
  profiles:
    active: production
  view:
    prefix: '/jsp/'
    suffix: '.jsp'
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework.boot.context.web.ErrorPageFilter: OFF
