logging:
  level: DEBUG

spring:
  datasource:
    initialize: true
    schema: classpath:test/schema.sql
    data: classpath:test/data.sql
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

liquibase:
  enabled: false

secrets:
  encrypt-once-password: tDVHRGFRsWB1fofGcT9MbuWPLsgwVE6QPc0SMOaViVe9MidtA5sFoBjwx55QhzEt
  encrypt-once-salt: bde1f26c24f303a2741f49571ac55e53988a7d5bca8d5c98a5bd98a5cd8a95dc8ad95c
  encrypt-queryable-password: ade1s26c25f30362747f49571ac55e73tDVHRGF7sWB1fofGc79MbuWPLsgwVE78
  encrypt-queryable-salt: b78ad6c6ad87ac6d4ba78a5bd7c5ad76c5a87d6587a65c67a8d5ca765da8c6

custom:
  oauth:
    authCode:
      expire-seconds: 600
    accessToken:
      expire-seconds: 600
    resource:
      access-limit-per-month: 25000
  openid:
    config-path: test/openid.properties
  management:
    security:
      access: hasIpAddress('127.0.0.1') or hasIpAddress('0:0:0:0:0:0:0:1')