logging:
  level: DEBUG

spring:
  datasource:
    initialize: true
    schema: classpath:test/schema.sql
    data: classpath:test/data.sql
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

liquibase:
  enabled: false

custom:
  oauth:
    authCode:
      expire-seconds: 600
    accessToken:
      expire-seconds: 600
    apiToken:
      expire-seconds: 600
    security:
        defaultSalt: tDVHRGFRsWB1fofGcT9MbuWPLsgwVE6Q
  openid:
    config-path: test/openid.properties
  api:
    limit-times: 25000
  management:
    security:
      access: hasIpAddress('127.0.0.1') or hasIpAddress('0:0:0:0:0:0:0:1')