logging:
  level: DEBUG

spring:
  datasource:
    initialize: true
    schema: classpath:test/schema.sql
    data: classpath:test/data.sql
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

liquibase:
  enabled: false

custom:
  oauth:
    authCode:
      expire-seconds: 600
    accessToken:
      expire-seconds: 600
  openid:
    config-path: test/openid.properties