server:
  port: 8181
spring:
  main:
    show_banner: false
  profiles:
    active: production
  view:
    prefix: '/jsp/'
    suffix: '.jsp'
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
